// Code generated by go yacc.
//line sql.y:6
package parser

import __yyfmt__ "fmt"

//line sql.y:6
import (
	"strconv"
	"strings"
)

func setParseTree(yylex interface{}, stmt Statement) {
	yylex.(*tokenizer).parseTree = stmt
}

func setAllowComments(yylex interface{}, allow bool) {
	yylex.(*tokenizer).allowComments = allow
}

func forceEOF(yylex interface{}) {
	yylex.(*tokenizer).forceEOF = true
}

func parseInt(yylex yyLexer, s string) (int, bool) {
	i, err := strconv.Atoi(s)
	if err != nil {
		yylex.Error(err.Error())
		return -1, false
	}
	return i, true
}

//line sql.y:36
type yySymType struct {
	yys         int
	empty       struct{}
	statement   Statement
	selStmt     SelectStatement
	byt         byte
	str         string
	str2        []string
	selectExprs SelectExprs
	selectExpr  SelectExpr
	columns     Columns
	colName     *ColName
	tableExprs  TableExprs
	tableExpr   TableExpr
	smTableExpr SimpleTableExpr
	tableName   *TableName
	indexHints  *IndexHints
	expr        Expr
	boolExpr    BoolExpr
	valExpr     ValExpr
	tuple       Tuple
	valExprs    ValExprs
	values      Values
	subquery    *Subquery
	caseExpr    *CaseExpr
	whens       []*When
	when        *When
	orderBy     OrderBy
	order       *Order
	limit       *Limit
	insRows     InsertRows
	updateExprs UpdateExprs
	updateExpr  *UpdateExpr
	tableDefs   TableDefs
	tableDef    TableDef
	columnType  ColumnType
	intVal      int
	intVal2     [2]int
	boolVal     bool
}

const tokLexError = 57346
const tokSelect = 57347
const tokInsert = 57348
const tokUpdate = 57349
const tokDelete = 57350
const tokFrom = 57351
const tokWhere = 57352
const tokGroup = 57353
const tokHaving = 57354
const tokOrder = 57355
const tokBy = 57356
const tokLimit = 57357
const tokOffset = 57358
const tokFor = 57359
const tokAll = 57360
const tokDistinct = 57361
const tokAs = 57362
const tokExists = 57363
const tokIn = 57364
const tokIs = 57365
const tokLike = 57366
const tokBetween = 57367
const tokNull = 57368
const tokAsc = 57369
const tokDesc = 57370
const tokValues = 57371
const tokInto = 57372
const tokDuplicate = 57373
const tokKey = 57374
const tokDefault = 57375
const tokSet = 57376
const tokLock = 57377
const tokInt = 57378
const tokTinyInt = 57379
const tokSmallInt = 57380
const tokMediumInt = 57381
const tokBigInt = 57382
const tokInteger = 57383
const tokReal = 57384
const tokDouble = 57385
const tokFloat = 57386
const tokDecimal = 57387
const tokNumeric = 57388
const tokDate = 57389
const tokTime = 57390
const tokDateTime = 57391
const tokTimestamp = 57392
const tokChar = 57393
const tokVarChar = 57394
const tokBinary = 57395
const tokVarBinary = 57396
const tokText = 57397
const tokTinyText = 57398
const tokMediumText = 57399
const tokLongText = 57400
const tokBlob = 57401
const tokTinyBlob = 57402
const tokMediumBlob = 57403
const tokLongBlob = 57404
const tokBit = 57405
const tokEnum = 57406
const tokID = 57407
const tokString = 57408
const tokNumber = 57409
const tokValueArg = 57410
const tokComment = 57411
const tokLE = 57412
const tokGE = 57413
const tokNE = 57414
const tokNullSafeEqual = 57415
const tokUnion = 57416
const tokMinus = 57417
const tokExcept = 57418
const tokIntersect = 57419
const tokJoin = 57420
const tokStraightJoin = 57421
const tokLeft = 57422
const tokRight = 57423
const tokInner = 57424
const tokOuter = 57425
const tokCross = 57426
const tokNatural = 57427
const tokUse = 57428
const tokForce = 57429
const tokOn = 57430
const tokUsing = 57431
const tokAnd = 57432
const tokOr = 57433
const tokNot = 57434
const tokUnary = 57435
const tokCase = 57436
const tokWhen = 57437
const tokThen = 57438
const tokElse = 57439
const tokEnd = 57440
const tokCreate = 57441
const tokAlter = 57442
const tokDrop = 57443
const tokRename = 57444
const tokTruncate = 57445
const tokShow = 57446
const tokDatabase = 57447
const tokDatabases = 57448
const tokTable = 57449
const tokTables = 57450
const tokIndex = 57451
const tokView = 57452
const tokColumns = 57453
const tokFull = 57454
const tokTo = 57455
const tokIgnore = 57456
const tokIf = 57457
const tokUnique = 57458
const tokUnsigned = 57459
const tokPrimary = 57460

var yyToknames = []string{
	"tokLexError",
	"tokSelect",
	"tokInsert",
	"tokUpdate",
	"tokDelete",
	"tokFrom",
	"tokWhere",
	"tokGroup",
	"tokHaving",
	"tokOrder",
	"tokBy",
	"tokLimit",
	"tokOffset",
	"tokFor",
	"tokAll",
	"tokDistinct",
	"tokAs",
	"tokExists",
	"tokIn",
	"tokIs",
	"tokLike",
	"tokBetween",
	"tokNull",
	"tokAsc",
	"tokDesc",
	"tokValues",
	"tokInto",
	"tokDuplicate",
	"tokKey",
	"tokDefault",
	"tokSet",
	"tokLock",
	"tokInt",
	"tokTinyInt",
	"tokSmallInt",
	"tokMediumInt",
	"tokBigInt",
	"tokInteger",
	"tokReal",
	"tokDouble",
	"tokFloat",
	"tokDecimal",
	"tokNumeric",
	"tokDate",
	"tokTime",
	"tokDateTime",
	"tokTimestamp",
	"tokChar",
	"tokVarChar",
	"tokBinary",
	"tokVarBinary",
	"tokText",
	"tokTinyText",
	"tokMediumText",
	"tokLongText",
	"tokBlob",
	"tokTinyBlob",
	"tokMediumBlob",
	"tokLongBlob",
	"tokBit",
	"tokEnum",
	"tokID",
	"tokString",
	"tokNumber",
	"tokValueArg",
	"tokComment",
	"tokLE",
	"tokGE",
	"tokNE",
	"tokNullSafeEqual",
	"'('",
	"'='",
	"'<'",
	"'>'",
	"'~'",
	"tokUnion",
	"tokMinus",
	"tokExcept",
	"tokIntersect",
	"','",
	"tokJoin",
	"tokStraightJoin",
	"tokLeft",
	"tokRight",
	"tokInner",
	"tokOuter",
	"tokCross",
	"tokNatural",
	"tokUse",
	"tokForce",
	"tokOn",
	"tokUsing",
	"tokAnd",
	"tokOr",
	"tokNot",
	"'&'",
	"'|'",
	"'^'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'.'",
	"tokUnary",
	"tokCase",
	"tokWhen",
	"tokThen",
	"tokElse",
	"tokEnd",
	"tokCreate",
	"tokAlter",
	"tokDrop",
	"tokRename",
	"tokTruncate",
	"tokShow",
	"tokDatabase",
	"tokDatabases",
	"tokTable",
	"tokTables",
	"tokIndex",
	"tokView",
	"tokColumns",
	"tokFull",
	"tokTo",
	"tokIgnore",
	"tokIf",
	"tokUnique",
	"tokUnsigned",
	"tokPrimary",
}
var yyStatenames = []string{}

const yyEofCode = 1
const yyErrCode = 2
const yyMaxDepth = 200

//line yacctab:1
var yyExca = []int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyNprod = 273
const yyPrivate = 57344

var yyTokenNames []string
var yyStates []string

const yyLast = 692

var yyAct = []int{

	107, 439, 393, 316, 446, 179, 67, 181, 263, 105,
	441, 266, 139, 400, 271, 220, 104, 257, 308, 470,
	470, 98, 492, 132, 182, 3, 197, 93, 94, 155,
	156, 481, 470, 115, 465, 116, 121, 314, 70, 72,
	28, 29, 30, 31, 442, 470, 89, 82, 112, 470,
	436, 85, 58, 470, 69, 470, 90, 283, 284, 285,
	286, 287, 150, 288, 289, 80, 99, 247, 320, 314,
	491, 490, 71, 111, 113, 114, 131, 133, 133, 150,
	133, 185, 138, 489, 140, 119, 279, 150, 488, 144,
	375, 377, 147, 148, 68, 250, 484, 152, 142, 249,
	473, 134, 143, 136, 471, 423, 469, 379, 183, 117,
	118, 422, 184, 383, 73, 78, 122, 50, 421, 319,
	313, 51, 84, 178, 180, 359, 70, 376, 191, 70,
	303, 201, 195, 81, 53, 200, 133, 120, 301, 57,
	384, 54, 69, 55, 56, 69, 188, 216, 52, 437,
	248, 435, 432, 433, 226, 201, 99, 258, 294, 203,
	217, 218, 258, 230, 306, 202, 235, 236, 231, 239,
	240, 241, 242, 243, 244, 245, 246, 228, 229, 225,
	48, 39, 274, 40, 41, 224, 42, 43, 154, 155,
	156, 251, 99, 99, 70, 70, 47, 130, 44, 126,
	262, 46, 73, 269, 386, 272, 398, 48, 276, 137,
	69, 264, 237, 207, 253, 255, 420, 261, 155, 156,
	268, 277, 265, 199, 163, 164, 165, 166, 167, 168,
	169, 170, 15, 168, 169, 170, 128, 213, 293, 296,
	297, 227, 295, 417, 418, 309, 280, 309, 110, 275,
	146, 419, 373, 115, 369, 300, 121, 211, 224, 370,
	99, 166, 167, 168, 169, 170, 429, 367, 112, 372,
	311, 371, 368, 198, 305, 198, 133, 315, 399, 128,
	307, 312, 302, 249, 238, 28, 29, 30, 31, 214,
	468, 466, 71, 111, 113, 114, 149, 365, 366, 361,
	430, 102, 388, 129, 382, 119, 458, 283, 284, 285,
	286, 287, 385, 288, 289, 70, 457, 224, 224, 390,
	456, 272, 455, 391, 394, 101, 15, 449, 185, 117,
	118, 389, 395, 428, 223, 396, 122, 402, 412, 210,
	212, 209, 410, 222, 407, 408, 281, 409, 128, 163,
	164, 165, 166, 167, 168, 169, 170, 120, 381, 193,
	411, 163, 164, 165, 166, 167, 168, 169, 170, 401,
	150, 406, 298, 404, 413, 163, 164, 165, 166, 167,
	168, 169, 170, 204, 189, 187, 223, 424, 186, 123,
	88, 73, 425, 292, 254, 222, 110, 71, 427, 194,
	153, 115, 380, 378, 121, 362, 444, 215, 445, 196,
	447, 447, 141, 447, 443, 448, 112, 450, 65, 87,
	86, 79, 251, 64, 453, 440, 451, 125, 486, 464,
	463, 426, 360, 462, 460, 461, 394, 452, 291, 454,
	97, 111, 113, 114, 387, 73, 487, 91, 92, 102,
	447, 15, 63, 119, 472, 474, 70, 447, 447, 447,
	70, 476, 477, 478, 475, 438, 479, 299, 480, 83,
	482, 483, 264, 101, 273, 260, 69, 117, 118, 95,
	110, 61, 494, 15, 122, 115, 205, 124, 121, 232,
	127, 233, 234, 145, 110, 495, 496, 45, 59, 115,
	112, 317, 121, 416, 115, 120, 318, 121, 267, 252,
	415, 32, 364, 198, 112, 135, 77, 76, 75, 112,
	15, 16, 17, 18, 97, 111, 113, 114, 34, 35,
	36, 37, 38, 102, 66, 493, 459, 119, 71, 111,
	113, 114, 15, 71, 111, 113, 114, 102, 33, 19,
	434, 119, 185, 397, 333, 332, 119, 101, 331, 330,
	325, 117, 118, 95, 158, 162, 160, 161, 122, 324,
	323, 101, 321, 270, 405, 117, 118, 403, 467, 74,
	117, 118, 122, 206, 278, 208, 49, 122, 192, 120,
	163, 164, 165, 166, 167, 168, 169, 170, 485, 431,
	392, 414, 363, 120, 304, 190, 256, 20, 120, 109,
	106, 108, 174, 175, 176, 177, 310, 171, 172, 173,
	103, 259, 157, 100, 374, 221, 282, 219, 96, 22,
	23, 26, 24, 25, 21, 290, 151, 60, 27, 62,
	159, 163, 164, 165, 166, 167, 168, 169, 170, 335,
	14, 336, 337, 338, 339, 340, 341, 342, 343, 344,
	345, 346, 326, 327, 328, 329, 347, 348, 349, 350,
	351, 352, 353, 354, 355, 356, 357, 358, 322, 334,
	13, 12, 11, 10, 9, 8, 7, 6, 5, 4,
	2, 1,
}
var yyPact = []int{

	515, -1000, -1000, 206, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 60, 76, -8, 26, 12, 19, 537, 480, -1000,
	-1000, -1000, 462, -1000, 422, 353, 525, 332, 326, -1000,
	509, 508, 507, -11, -65, 9, 326, -65, -1000, 0,
	326, -1000, 355, 354, -84, 326, -84, -84, -1000, -1000,
	459, -1000, 320, 353, 393, 92, 353, 196, -1000, 228,
	-1000, 90, -1000, -1000, -1000, 326, 326, 326, 506, 326,
	111, 326, -1000, 326, 347, -1000, -26, -1000, 326, 472,
	156, 326, 326, 287, -1000, -1000, 380, 81, 122, 542,
	-1000, 473, 227, -1000, -1000, -1000, 7, 314, 311, -1000,
	310, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 7, -1000, 325, 332, 344, 503, 332, 7,
	326, -1000, -1000, 58, -1000, 326, 309, 465, 118, -1000,
	-1000, 224, -1000, 342, -1000, -1000, 326, -1000, -1000, 269,
	459, -1000, -1000, 326, 137, 473, 473, 7, 254, 467,
	7, 7, 186, 7, 7, 7, 7, 7, 7, 7,
	7, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 542,
	-67, 16, -39, 542, -1000, 478, 375, 459, -1000, 537,
	47, 491, 446, 332, 332, 265, -1000, 495, 473, -1000,
	491, -1000, 326, -1000, 49, -1000, 155, 326, -1000, -42,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 263,
	223, 373, 321, 51, -1000, -1000, -1000, -1000, -1000, -1000,
	491, -1000, 254, 7, 7, 491, 276, -1000, 441, 159,
	159, 159, 129, 129, -1000, -1000, -1000, -1000, -1000, 7,
	-1000, 491, -1000, 4, 459, -4, 52, -1000, 473, 151,
	254, 206, 153, -14, -1000, 495, 486, 492, 122, -1000,
	-15, -1000, 615, 1, 400, 326, -1000, -1000, 340, -1000,
	501, 269, 269, -1000, -1000, 183, 170, 187, 185, 168,
	-2, -1000, 338, -27, 337, -1000, 491, 262, 7, -1000,
	491, -1000, -21, -1000, 27, -1000, 7, 93, -1000, 413,
	219, -1000, -1000, -1000, 332, 486, -1000, 7, 7, -1000,
	49, 180, 295, 295, 299, 297, -1000, -1000, -1000, -1000,
	295, 295, -1000, -1000, 273, 268, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 326,
	264, -1000, -1000, 498, 489, 223, 149, -1000, 167, -1000,
	132, -1000, -1000, -1000, -1000, -6, -13, -19, -1000, -1000,
	-1000, 7, 491, -1000, -1000, 491, 7, 399, 254, -1000,
	-1000, 250, 217, -1000, 125, -1000, -1000, 18, -1000, 439,
	-1000, 384, -88, -88, 384, -1000, 384, -1000, -1000, 326,
	326, 253, 326, -1000, 495, 473, 7, 473, 248, -1000,
	-1000, 246, 242, 232, 491, 491, 529, -1000, 7, 7,
	7, -1000, -1000, -1000, -1000, 398, -1000, 397, -1000, -100,
	-1000, -1000, -1000, -1000, 208, 207, -28, -1000, -30, 326,
	-34, 486, 122, 200, 122, 332, 326, 326, 326, 332,
	491, 491, -1000, -1000, -1000, -1000, 384, -103, 384, -1000,
	326, -1000, -38, -1000, 411, -46, -51, -63, -64, 196,
	-112, -1000, -1000, -1000, -1000, -1000, 528, 460, -1000, -1000,
	-1000, -1000, -1000, -1000, 326, 326, -1000,
}
var yyPgo = []int{

	0, 691, 690, 24, 689, 688, 687, 686, 685, 684,
	683, 682, 681, 680, 650, 511, 639, 638, 637, 27,
	28, 636, 635, 628, 627, 15, 626, 625, 423, 23,
	624, 4, 26, 21, 623, 622, 621, 620, 5, 9,
	7, 616, 611, 35, 610, 16, 609, 606, 17, 605,
	604, 602, 601, 11, 600, 2, 599, 3, 598, 588,
	8, 18, 6, 94, 586, 585, 584, 583, 10, 390,
	421, 474, 579, 13, 1, 578, 577, 574, 0, 573,
	14, 572, 570, 569, 560, 559, 558, 555, 554, 553,
	550, 12, 548,
}
var yyR1 = []int{

	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 3, 3, 4, 4, 5, 6,
	7, 8, 9, 9, 9, 9, 9, 10, 10, 10,
	10, 79, 79, 80, 80, 80, 81, 81, 81, 81,
	81, 81, 81, 81, 81, 81, 81, 81, 81, 81,
	82, 82, 82, 82, 82, 82, 83, 83, 83, 84,
	84, 85, 85, 86, 86, 87, 87, 87, 87, 88,
	88, 88, 88, 89, 89, 89, 90, 90, 90, 90,
	90, 11, 11, 11, 12, 13, 14, 14, 14, 14,
	92, 15, 16, 16, 17, 17, 17, 17, 17, 18,
	18, 19, 19, 20, 20, 20, 23, 23, 21, 21,
	21, 24, 24, 25, 25, 25, 25, 25, 22, 22,
	22, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	27, 27, 27, 28, 28, 29, 29, 30, 30, 30,
	30, 31, 31, 32, 32, 33, 33, 33, 33, 33,
	34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
	35, 35, 35, 35, 35, 35, 35, 36, 36, 41,
	41, 39, 39, 43, 40, 40, 38, 38, 38, 38,
	38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
	38, 38, 38, 42, 42, 44, 44, 44, 46, 49,
	49, 47, 47, 48, 50, 50, 45, 45, 37, 37,
	37, 37, 37, 51, 51, 52, 52, 53, 53, 54,
	54, 55, 56, 56, 56, 57, 57, 57, 57, 58,
	58, 58, 59, 59, 60, 60, 61, 61, 62, 62,
	63, 69, 69, 70, 70, 64, 64, 65, 65, 65,
	65, 65, 66, 66, 71, 71, 73, 73, 74, 76,
	76, 77, 77, 75, 75, 68, 68, 67, 67, 72,
	72, 78, 91,
}
var yyR2 = []int{

	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 12, 3, 7, 7, 8, 7,
	3, 3, 2, 3, 4, 4, 5, 8, 8, 4,
	4, 1, 3, 4, 6, 5, 2, 3, 3, 2,
	1, 1, 1, 1, 2, 2, 1, 1, 4, 4,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 0, 1, 2, 0, 2, 1, 1,
	2, 6, 7, 4, 5, 3, 4, 5, 5, 5,
	0, 2, 0, 2, 1, 2, 1, 1, 1, 0,
	1, 1, 3, 1, 2, 3, 1, 1, 0, 1,
	2, 1, 3, 3, 3, 3, 5, 7, 0, 1,
	2, 1, 1, 2, 3, 2, 3, 2, 2, 2,
	1, 3, 1, 1, 3, 1, 3, 0, 5, 5,
	5, 1, 3, 0, 2, 1, 3, 3, 2, 3,
	3, 3, 4, 3, 4, 5, 6, 3, 4, 2,
	1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
	3, 3, 1, 3, 1, 3, 1, 1, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 2, 3, 4,
	5, 4, 1, 1, 1, 1, 1, 1, 5, 0,
	1, 1, 2, 4, 0, 2, 1, 3, 1, 1,
	1, 1, 1, 0, 3, 0, 2, 0, 3, 1,
	3, 2, 0, 1, 1, 0, 2, 4, 4, 0,
	2, 4, 0, 3, 1, 3, 0, 5, 1, 3,
	3, 0, 2, 0, 3, 0, 1, 1, 1, 1,
	1, 1, 0, 1, 0, 1, 0, 3, 1, 0,
	5, 0, 4, 0, 2, 0, 1, 0, 2, 0,
	2, 1, 0,
}
var yyChk = []int{

	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -11, -12, -13, -14, 5, 6, 7, 8, 34,
	92, 119, 114, 115, 117, 118, 116, -17, 79, 80,
	81, 82, -15, -92, -15, -15, -15, -15, -15, 121,
	123, 124, 126, 127, 122, -71, 125, 120, 131, -64,
	125, 129, 122, 122, 122, 124, 125, 120, -3, 18,
	-18, 19, -16, 30, -28, 65, 9, -62, -63, -45,
	-78, 65, -78, 65, -72, 9, 9, 9, 126, -70,
	130, 124, -78, -70, 122, -78, 65, 65, -69, 130,
	-78, -69, -69, -19, -20, 104, -23, 65, -33, -38,
	-34, 98, 74, -37, -45, -39, -44, -78, -42, -46,
	21, 66, 41, 67, 68, 26, -43, 102, 103, 78,
	130, 29, 109, 69, -28, 34, 107, -28, 83, 75,
	107, -78, -29, -78, -29, 9, -29, 98, -78, -91,
	-78, 65, -91, 128, -78, 21, 94, -78, -78, 9,
	83, -21, -78, 20, 107, 96, 97, -35, 22, 98,
	24, 25, 23, 99, 100, 101, 102, 103, 104, 105,
	106, 75, 76, 77, 70, 71, 72, 73, -33, -38,
	-33, -40, -3, -38, -38, 74, 74, 74, -43, 74,
	-49, -38, -59, 34, 74, -62, 65, -32, 10, -63,
	-38, -78, 107, -29, 74, 21, -67, 95, -65, 117,
	115, 33, 116, 13, 65, 65, -78, -91, -91, -24,
	-25, -27, 74, 65, -43, -20, -78, 104, -33, -33,
	-38, -39, 22, 24, 25, -38, -38, 26, 98, -38,
	-38, -38, -38, -38, -38, -38, -38, 134, 134, 83,
	134, -38, 134, -19, 19, -19, -47, -48, 110, -36,
	29, -3, -62, -60, -45, -32, -53, 13, -33, -78,
	-79, -80, -78, -71, 133, 94, -78, -91, -66, 128,
	-32, 83, -26, 84, 85, 86, 87, 88, 90, 91,
	-22, 65, 20, -25, 107, -39, -38, -38, 96, 26,
	-38, 134, -19, 134, -50, -48, 112, -33, -61, 94,
	-41, -39, -61, 134, 83, -53, -57, 15, 14, 134,
	83, -81, 63, -82, -83, -84, 47, 48, 49, 50,
	-85, -86, -87, -88, 64, 34, 36, 37, 38, 39,
	40, 41, 42, 43, 44, 45, 46, 51, 52, 53,
	54, 55, 56, 57, 58, 59, 60, 61, 62, 124,
	32, -29, 65, -51, 11, -25, -25, 84, 89, 84,
	89, 84, 84, 84, -30, 92, 129, 93, 65, 134,
	65, 96, -38, 134, 113, -38, 111, 31, 83, -45,
	-57, -38, -54, -55, -38, -91, -80, -89, 26, 98,
	-73, 74, -73, -76, 74, -77, 74, -73, -73, 74,
	74, -78, 74, -91, -52, 12, 14, 94, 95, 84,
	84, 124, 124, 124, -38, -38, 32, -39, 83, 16,
	83, -56, 27, 28, -90, 133, 32, 131, 26, -74,
	41, -68, 132, -68, -74, -74, -31, -78, -31, 74,
	-31, -53, -33, -40, -33, 74, 74, 74, 74, 7,
	-38, -38, -55, 32, 32, 134, 83, -75, 83, 134,
	83, 134, -31, 134, -57, -60, -31, -31, -31, -62,
	-74, 134, -74, -78, 134, -58, 17, 35, 134, 134,
	134, 134, 134, 7, 22, -78, -78,
}
var yyDef = []int{

	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	9, 10, 11, 12, 13, 90, 90, 90, 90, 90,
	90, 0, 254, 245, 0, 0, 0, 0, 94, 96,
	97, 98, 99, 92, 0, 0, 0, 0, 0, 22,
	269, 0, 0, 0, 243, 0, 0, 243, 255, 0,
	0, 246, 0, 0, 241, 0, 241, 241, 15, 95,
	0, 100, 91, 0, 0, 133, 0, 20, 238, 0,
	206, 271, 21, 271, 23, 0, 0, 0, 0, 0,
	0, 0, 272, 0, 0, 272, 0, 85, 0, 0,
	0, 0, 0, 0, 101, 103, 108, 271, 106, 107,
	145, 0, 0, 176, 177, 178, 0, 206, 0, 192,
	0, 208, 209, 210, 211, 212, 172, 195, 196, 197,
	193, 194, 199, 93, 232, 0, 0, 143, 0, 0,
	0, 270, 24, 135, 25, 0, 0, 0, 267, 29,
	30, 0, 83, 0, 86, 242, 0, 272, 272, 0,
	0, 104, 109, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 160, 161, 162, 163, 164, 165, 166, 148, 0,
	0, 0, 0, 174, 187, 0, 0, 0, 159, 0,
	0, 200, 0, 0, 0, 143, 134, 217, 0, 239,
	240, 207, 0, 26, 254, 244, 0, 0, 272, 252,
	247, 248, 249, 250, 251, 84, 87, 88, 89, 143,
	111, 118, 0, 130, 132, 102, 110, 105, 146, 147,
	150, 151, 0, 0, 0, 153, 0, 157, 0, 179,
	180, 181, 182, 183, 184, 185, 186, 149, 171, 0,
	173, 174, 188, 0, 0, 0, 204, 201, 0, 236,
	0, 168, 236, 0, 234, 217, 225, 0, 144, 136,
	0, 31, 0, 0, 0, 0, 268, 81, 0, 253,
	213, 0, 0, 121, 122, 0, 0, 0, 0, 0,
	137, 119, 0, 0, 0, 152, 154, 0, 0, 158,
	175, 189, 0, 191, 0, 202, 0, 0, 16, 0,
	167, 169, 17, 233, 0, 225, 19, 0, 0, 272,
	254, 73, 256, 256, 259, 261, 40, 41, 42, 43,
	256, 256, 46, 47, 0, 0, 50, 51, 52, 53,
	54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
	64, 65, 66, 67, 68, 69, 70, 71, 72, 0,
	0, 272, 82, 215, 0, 112, 115, 123, 0, 125,
	0, 127, 128, 129, 113, 0, 0, 0, 120, 114,
	131, 0, 155, 190, 198, 205, 0, 0, 0, 235,
	18, 226, 218, 219, 222, 27, 32, 76, 74, 0,
	36, 0, 265, 265, 0, 39, 0, 44, 45, 0,
	0, 0, 0, 28, 217, 0, 0, 0, 0, 124,
	126, 0, 0, 0, 156, 203, 0, 170, 0, 0,
	0, 221, 223, 224, 33, 0, 78, 79, 75, 0,
	258, 37, 266, 38, 0, 263, 0, 141, 0, 0,
	0, 225, 216, 214, 116, 0, 0, 0, 0, 0,
	227, 228, 220, 77, 80, 257, 0, 0, 0, 48,
	0, 49, 0, 35, 229, 0, 0, 0, 0, 237,
	0, 262, 264, 142, 34, 14, 0, 0, 117, 138,
	139, 140, 260, 230, 0, 0, 231,
}
var yyTok1 = []int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 106, 99, 3,
	74, 134, 104, 102, 83, 103, 107, 105, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	76, 75, 77, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 101, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 100, 3, 78,
}
var yyTok2 = []int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 79, 80, 81, 82, 84, 85, 86, 87,
	88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
	98, 108, 109, 110, 111, 112, 113, 114, 115, 116,
	117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
	127, 128, 129, 130, 131, 132, 133,
}
var yyTok3 = []int{
	0,
}

//line yaccpar:1

/*	parser for yacc output	*/

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

const yyFlag = -1000

func yyTokname(c int) string {
	// 4 is TOKSTART above
	if c >= 4 && c-4 < len(yyToknames) {
		if yyToknames[c-4] != "" {
			return yyToknames[c-4]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yylex1(lex yyLexer, lval *yySymType) int {
	c := 0
	char := lex.Lex(lval)
	if char <= 0 {
		c = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		c = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			c = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		c = yyTok3[i+0]
		if c == char {
			c = yyTok3[i+1]
			goto out
		}
	}

out:
	if c == 0 {
		c = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(c), uint(char))
	}
	return c
}

func yyParse(yylex yyLexer) int {
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, yyMaxDepth)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yychar := -1
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yychar), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yychar < 0 {
		yychar = yylex1(yylex, &yylval)
	}
	yyn += yychar
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yychar { /* valid shift */
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yychar < 0 {
			yychar = yylex1(yylex, &yylval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yychar {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error("syntax error")
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yychar))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}
			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		//line sql.y:173
		{
			setParseTree(yylex, yyS[yypt-0].statement)
		}
	case 2:
		//line sql.y:179
		{
			yyVAL.statement = yyS[yypt-0].selStmt
		}
	case 3:
		yyVAL.statement = yyS[yypt-0].statement
	case 4:
		yyVAL.statement = yyS[yypt-0].statement
	case 5:
		yyVAL.statement = yyS[yypt-0].statement
	case 6:
		yyVAL.statement = yyS[yypt-0].statement
	case 7:
		yyVAL.statement = yyS[yypt-0].statement
	case 8:
		yyVAL.statement = yyS[yypt-0].statement
	case 9:
		yyVAL.statement = yyS[yypt-0].statement
	case 10:
		yyVAL.statement = yyS[yypt-0].statement
	case 11:
		yyVAL.statement = yyS[yypt-0].statement
	case 12:
		yyVAL.statement = yyS[yypt-0].statement
	case 13:
		yyVAL.statement = yyS[yypt-0].statement
	case 14:
		//line sql.y:196
		{
			yyVAL.selStmt = &Select{Comments: Comments(yyS[yypt-10].str2), Distinct: yyS[yypt-9].str, Exprs: yyS[yypt-8].selectExprs, From: yyS[yypt-6].tableExprs, Where: NewWhere(astWhere, yyS[yypt-5].boolExpr), GroupBy: GroupBy(yyS[yypt-4].valExprs), Having: NewWhere(astHaving, yyS[yypt-3].boolExpr), OrderBy: yyS[yypt-2].orderBy, Limit: yyS[yypt-1].limit, Lock: yyS[yypt-0].str}
		}
	case 15:
		//line sql.y:200
		{
			yyVAL.selStmt = &Union{Type: yyS[yypt-1].str, Left: yyS[yypt-2].selStmt, Right: yyS[yypt-0].selStmt}
		}
	case 16:
		//line sql.y:206
		{
			yyVAL.statement = &Insert{Comments: Comments(yyS[yypt-5].str2), Table: yyS[yypt-3].tableName, Columns: yyS[yypt-2].columns, Rows: yyS[yypt-1].insRows, OnDup: OnDup(yyS[yypt-0].updateExprs)}
		}
	case 17:
		//line sql.y:210
		{
			cols := make(Columns, 0, len(yyS[yypt-1].updateExprs))
			vals := make(ValTuple, 0, len(yyS[yypt-1].updateExprs))
			for _, col := range yyS[yypt-1].updateExprs {
				cols = append(cols, &NonStarExpr{Expr: col.Name})
				vals = append(vals, col.Expr)
			}
			yyVAL.statement = &Insert{Comments: Comments(yyS[yypt-5].str2), Table: yyS[yypt-3].tableName, Columns: cols, Rows: Values{vals}, OnDup: OnDup(yyS[yypt-0].updateExprs)}
		}
	case 18:
		//line sql.y:222
		{
			yyVAL.statement = &Update{Comments: Comments(yyS[yypt-6].str2), Table: yyS[yypt-5].tableName, Exprs: yyS[yypt-3].updateExprs, Where: NewWhere(astWhere, yyS[yypt-2].boolExpr), OrderBy: yyS[yypt-1].orderBy, Limit: yyS[yypt-0].limit}
		}
	case 19:
		//line sql.y:228
		{
			yyVAL.statement = &Delete{Comments: Comments(yyS[yypt-5].str2), Table: yyS[yypt-3].tableName, Where: NewWhere(astWhere, yyS[yypt-2].boolExpr), OrderBy: yyS[yypt-1].orderBy, Limit: yyS[yypt-0].limit}
		}
	case 20:
		//line sql.y:234
		{
			yyVAL.statement = &Set{Comments: Comments(yyS[yypt-1].str2), Exprs: yyS[yypt-0].updateExprs}
		}
	case 21:
		//line sql.y:240
		{
			yyVAL.statement = &Use{Comments: Comments(yyS[yypt-1].str2), Name: yyS[yypt-0].str}
		}
	case 22:
		//line sql.y:246
		{
			yyVAL.statement = &ShowDatabases{}
		}
	case 23:
		//line sql.y:250
		{
			yyVAL.statement = &ShowTables{Name: yyS[yypt-0].str}
		}
	case 24:
		//line sql.y:254
		{
			yyVAL.statement = &ShowIndex{Table: yyS[yypt-0].tableName}
		}
	case 25:
		//line sql.y:258
		{
			yyVAL.statement = &ShowColumns{Table: yyS[yypt-0].tableName}
		}
	case 26:
		//line sql.y:262
		{
			yyVAL.statement = &ShowColumns{Table: yyS[yypt-0].tableName, Full: true}
		}
	case 27:
		//line sql.y:268
		{
			yyVAL.statement = &CreateTable{IfNotExists: yyS[yypt-5].boolVal, Table: yyS[yypt-4].tableName, Defs: yyS[yypt-2].tableDefs}
		}
	case 28:
		//line sql.y:272
		{
			yyVAL.statement = &CreateIndex{Name: yyS[yypt-4].str, Table: yyS[yypt-1].tableName, Unique: yyS[yypt-6].boolVal}
		}
	case 29:
		//line sql.y:276
		{
			yyVAL.statement = &CreateView{Name: yyS[yypt-1].str}
		}
	case 30:
		//line sql.y:280
		{
			yyVAL.statement = &CreateDatabase{IfNotExists: yyS[yypt-1].boolVal, Name: yyS[yypt-0].str}
		}
	case 31:
		//line sql.y:286
		{
			yyVAL.tableDefs = TableDefs{yyS[yypt-0].tableDef}
		}
	case 32:
		//line sql.y:290
		{
			yyVAL.tableDefs = append(yyVAL.tableDefs, yyS[yypt-0].tableDef)
		}
	case 33:
		//line sql.y:296
		{
			yyVAL.tableDef = &ColumnTableDef{Name: yyS[yypt-3].str, Type: yyS[yypt-2].columnType, Nullable: Nullability(yyS[yypt-1].intVal), PrimaryKey: yyS[yypt-0].intVal == 1, Unique: yyS[yypt-0].intVal == 2}
		}
	case 34:
		//line sql.y:300
		{
			yyVAL.tableDef = &IndexTableDef{Name: yyS[yypt-3].str, Unique: yyS[yypt-5].boolVal, Columns: yyS[yypt-1].str2}
		}
	case 35:
		//line sql.y:304
		{
			yyVAL.tableDef = &IndexTableDef{Name: "primary", PrimaryKey: true, Unique: true, Columns: yyS[yypt-1].str2}
		}
	case 36:
		//line sql.y:310
		{
			yyVAL.columnType = &BitType{N: yyS[yypt-0].intVal}
		}
	case 37:
		//line sql.y:312
		{
			yyVAL.columnType = &IntType{Name: yyS[yypt-2].str, N: yyS[yypt-1].intVal, Unsigned: yyS[yypt-0].boolVal}
		}
	case 38:
		//line sql.y:314
		{
			yyVAL.columnType = &FloatType{Name: yyS[yypt-2].str, N: yyS[yypt-1].intVal2[0], Prec: yyS[yypt-1].intVal2[1], Unsigned: yyS[yypt-0].boolVal}
		}
	case 39:
		//line sql.y:316
		{
			yyVAL.columnType = &DecimalType{Name: yyS[yypt-1].str, N: yyS[yypt-0].intVal2[0], Prec: yyS[yypt-0].intVal2[1]}
		}
	case 40:
		//line sql.y:318
		{
			yyVAL.columnType = &DateType{}
		}
	case 41:
		//line sql.y:320
		{
			yyVAL.columnType = &TimeType{}
		}
	case 42:
		//line sql.y:322
		{
			yyVAL.columnType = &DateTimeType{}
		}
	case 43:
		//line sql.y:324
		{
			yyVAL.columnType = &TimestampType{}
		}
	case 44:
		//line sql.y:326
		{
			yyVAL.columnType = &CharType{Name: yyS[yypt-1].str, N: yyS[yypt-0].intVal}
		}
	case 45:
		//line sql.y:328
		{
			yyVAL.columnType = &BinaryType{Name: yyS[yypt-1].str, N: yyS[yypt-0].intVal}
		}
	case 46:
		//line sql.y:330
		{
			yyVAL.columnType = &TextType{Name: yyS[yypt-0].str}
		}
	case 47:
		//line sql.y:332
		{
			yyVAL.columnType = &BlobType{Name: yyS[yypt-0].str}
		}
	case 48:
		//line sql.y:334
		{
			yyVAL.columnType = &EnumType{Vals: yyS[yypt-1].str2}
		}
	case 49:
		//line sql.y:336
		{
			yyVAL.columnType = &SetType{Vals: yyS[yypt-1].str2}
		}
	case 50:
		//line sql.y:340
		{
			yyVAL.str = astInt
		}
	case 51:
		//line sql.y:342
		{
			yyVAL.str = astTinyInt
		}
	case 52:
		//line sql.y:344
		{
			yyVAL.str = astSmallInt
		}
	case 53:
		//line sql.y:346
		{
			yyVAL.str = astMediumInt
		}
	case 54:
		//line sql.y:348
		{
			yyVAL.str = astBigInt
		}
	case 55:
		//line sql.y:350
		{
			yyVAL.str = astInteger
		}
	case 56:
		//line sql.y:354
		{
			yyVAL.str = astReal
		}
	case 57:
		//line sql.y:356
		{
			yyVAL.str = astDouble
		}
	case 58:
		//line sql.y:358
		{
			yyVAL.str = astFloat
		}
	case 59:
		//line sql.y:362
		{
			yyVAL.str = astDecimal
		}
	case 60:
		//line sql.y:364
		{
			yyVAL.str = astNumeric
		}
	case 61:
		//line sql.y:368
		{
			yyVAL.str = astChar
		}
	case 62:
		//line sql.y:370
		{
			yyVAL.str = astVarChar
		}
	case 63:
		//line sql.y:374
		{
			yyVAL.str = astBinary
		}
	case 64:
		//line sql.y:376
		{
			yyVAL.str = astVarBinary
		}
	case 65:
		//line sql.y:380
		{
			yyVAL.str = astText
		}
	case 66:
		//line sql.y:382
		{
			yyVAL.str = astTinyText
		}
	case 67:
		//line sql.y:384
		{
			yyVAL.str = astMediumText
		}
	case 68:
		//line sql.y:386
		{
			yyVAL.str = astLongText
		}
	case 69:
		//line sql.y:390
		{
			yyVAL.str = astBlob
		}
	case 70:
		//line sql.y:392
		{
			yyVAL.str = astTinyBlob
		}
	case 71:
		//line sql.y:394
		{
			yyVAL.str = astMediumBlob
		}
	case 72:
		//line sql.y:396
		{
			yyVAL.str = astLongBlob
		}
	case 73:
		//line sql.y:399
		{
			yyVAL.intVal = int(SilentNull)
		}
	case 74:
		//line sql.y:401
		{
			yyVAL.intVal = int(Null)
		}
	case 75:
		//line sql.y:403
		{
			yyVAL.intVal = int(NotNull)
		}
	case 76:
		//line sql.y:406
		{
			yyVAL.intVal = 0
		}
	case 77:
		//line sql.y:408
		{
			yyVAL.intVal = 1
		}
	case 78:
		//line sql.y:410
		{
			yyVAL.intVal = 1
		}
	case 79:
		//line sql.y:412
		{
			yyVAL.intVal = 2
		}
	case 80:
		//line sql.y:414
		{
			yyVAL.intVal = 2
		}
	case 81:
		//line sql.y:418
		{
			yyVAL.statement = &AlterTable{Name: yyS[yypt-2].str}
		}
	case 82:
		//line sql.y:422
		{
			// Change this to a rename statement
			yyVAL.statement = &RenameTable{Name: yyS[yypt-3].str, NewName: yyS[yypt-0].str}
		}
	case 83:
		//line sql.y:427
		{
			yyVAL.statement = &AlterView{Name: yyS[yypt-1].str}
		}
	case 84:
		//line sql.y:433
		{
			yyVAL.statement = &RenameTable{Name: yyS[yypt-2].str, NewName: yyS[yypt-0].str}
		}
	case 85:
		//line sql.y:439
		{
			yyVAL.statement = &TruncateTable{Name: yyS[yypt-0].str}
		}
	case 86:
		//line sql.y:445
		{
			yyVAL.statement = &DropTable{Name: yyS[yypt-0].str, IfExists: yyS[yypt-1].boolVal}
		}
	case 87:
		//line sql.y:449
		{
			yyVAL.statement = &DropIndex{Name: yyS[yypt-2].str, TableName: yyS[yypt-0].str}
		}
	case 88:
		//line sql.y:453
		{
			yyVAL.statement = &DropView{Name: yyS[yypt-1].str, IfExists: yyS[yypt-2].boolVal}
		}
	case 89:
		//line sql.y:457
		{
			yyVAL.statement = &DropDatabase{Name: yyS[yypt-1].str, IfExists: yyS[yypt-2].boolVal}
		}
	case 90:
		//line sql.y:462
		{
			setAllowComments(yylex, true)
		}
	case 91:
		//line sql.y:466
		{
			yyVAL.str2 = yyS[yypt-0].str2
			setAllowComments(yylex, false)
		}
	case 92:
		//line sql.y:472
		{
			yyVAL.str2 = nil
		}
	case 93:
		//line sql.y:476
		{
			yyVAL.str2 = append(yyS[yypt-1].str2, yyS[yypt-0].str)
		}
	case 94:
		//line sql.y:482
		{
			yyVAL.str = astUnion
		}
	case 95:
		//line sql.y:486
		{
			yyVAL.str = astUnionAll
		}
	case 96:
		//line sql.y:490
		{
			yyVAL.str = astSetMinus
		}
	case 97:
		//line sql.y:494
		{
			yyVAL.str = astExcept
		}
	case 98:
		//line sql.y:498
		{
			yyVAL.str = astIntersect
		}
	case 99:
		//line sql.y:503
		{
			yyVAL.str = ""
		}
	case 100:
		//line sql.y:507
		{
			yyVAL.str = astDistinct
		}
	case 101:
		//line sql.y:513
		{
			yyVAL.selectExprs = SelectExprs{yyS[yypt-0].selectExpr}
		}
	case 102:
		//line sql.y:517
		{
			yyVAL.selectExprs = append(yyVAL.selectExprs, yyS[yypt-0].selectExpr)
		}
	case 103:
		//line sql.y:523
		{
			yyVAL.selectExpr = &StarExpr{}
		}
	case 104:
		//line sql.y:527
		{
			yyVAL.selectExpr = &NonStarExpr{Expr: yyS[yypt-1].expr, As: yyS[yypt-0].str}
		}
	case 105:
		//line sql.y:531
		{
			yyVAL.selectExpr = &StarExpr{TableName: yyS[yypt-2].str}
		}
	case 106:
		//line sql.y:537
		{
			yyVAL.expr = yyS[yypt-0].boolExpr
		}
	case 107:
		//line sql.y:541
		{
			yyVAL.expr = yyS[yypt-0].valExpr
		}
	case 108:
		//line sql.y:546
		{
			yyVAL.str = ""
		}
	case 109:
		//line sql.y:550
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 110:
		//line sql.y:554
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 111:
		//line sql.y:560
		{
			yyVAL.tableExprs = TableExprs{yyS[yypt-0].tableExpr}
		}
	case 112:
		//line sql.y:564
		{
			yyVAL.tableExprs = append(yyVAL.tableExprs, yyS[yypt-0].tableExpr)
		}
	case 113:
		//line sql.y:570
		{
			yyVAL.tableExpr = &AliasedTableExpr{Expr: yyS[yypt-2].smTableExpr, As: yyS[yypt-1].str, Hints: yyS[yypt-0].indexHints}
		}
	case 114:
		//line sql.y:574
		{
			yyVAL.tableExpr = &ParenTableExpr{Expr: yyS[yypt-1].tableExpr}
		}
	case 115:
		//line sql.y:578
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyS[yypt-2].tableExpr, Join: yyS[yypt-1].str, RightExpr: yyS[yypt-0].tableExpr}
		}
	case 116:
		//line sql.y:582
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyS[yypt-4].tableExpr, Join: yyS[yypt-3].str, RightExpr: yyS[yypt-2].tableExpr, Cond: &OnJoinCond{yyS[yypt-0].boolExpr}}
		}
	case 117:
		//line sql.y:586
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyS[yypt-6].tableExpr, Join: yyS[yypt-5].str, RightExpr: yyS[yypt-4].tableExpr, Cond: &UsingJoinCond{yyS[yypt-1].columns}}
		}
	case 118:
		//line sql.y:591
		{
			yyVAL.str = ""
		}
	case 119:
		//line sql.y:595
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 120:
		//line sql.y:599
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 121:
		//line sql.y:605
		{
			yyVAL.str = astJoin
		}
	case 122:
		//line sql.y:609
		{
			yyVAL.str = astStraightJoin
		}
	case 123:
		//line sql.y:613
		{
			yyVAL.str = astLeftJoin
		}
	case 124:
		//line sql.y:617
		{
			yyVAL.str = astLeftJoin
		}
	case 125:
		//line sql.y:621
		{
			yyVAL.str = astRightJoin
		}
	case 126:
		//line sql.y:625
		{
			yyVAL.str = astRightJoin
		}
	case 127:
		//line sql.y:629
		{
			yyVAL.str = astJoin
		}
	case 128:
		//line sql.y:633
		{
			yyVAL.str = astCrossJoin
		}
	case 129:
		//line sql.y:637
		{
			yyVAL.str = astNaturalJoin
		}
	case 130:
		//line sql.y:643
		{
			yyVAL.smTableExpr = &TableName{Name: yyS[yypt-0].str}
		}
	case 131:
		//line sql.y:647
		{
			yyVAL.smTableExpr = &TableName{Qualifier: yyS[yypt-2].str, Name: yyS[yypt-0].str}
		}
	case 132:
		//line sql.y:651
		{
			yyVAL.smTableExpr = yyS[yypt-0].subquery
		}
	case 133:
		//line sql.y:657
		{
			yyVAL.tableName = &TableName{Name: yyS[yypt-0].str}
		}
	case 134:
		//line sql.y:661
		{
			yyVAL.tableName = &TableName{Qualifier: yyS[yypt-2].str, Name: yyS[yypt-0].str}
		}
	case 135:
		//line sql.y:667
		{
			yyVAL.tableName = &TableName{Name: yyS[yypt-0].str}
		}
	case 136:
		//line sql.y:671
		{
			yyVAL.tableName = &TableName{Qualifier: yyS[yypt-2].str, Name: yyS[yypt-0].str}
		}
	case 137:
		//line sql.y:676
		{
			yyVAL.indexHints = nil
		}
	case 138:
		//line sql.y:680
		{
			yyVAL.indexHints = &IndexHints{Type: astUse, Indexes: yyS[yypt-1].str2}
		}
	case 139:
		//line sql.y:684
		{
			yyVAL.indexHints = &IndexHints{Type: astIgnore, Indexes: yyS[yypt-1].str2}
		}
	case 140:
		//line sql.y:688
		{
			yyVAL.indexHints = &IndexHints{Type: astForce, Indexes: yyS[yypt-1].str2}
		}
	case 141:
		//line sql.y:694
		{
			yyVAL.str2 = []string{yyS[yypt-0].str}
		}
	case 142:
		//line sql.y:698
		{
			yyVAL.str2 = append(yyS[yypt-2].str2, yyS[yypt-0].str)
		}
	case 143:
		//line sql.y:703
		{
			yyVAL.boolExpr = nil
		}
	case 144:
		//line sql.y:707
		{
			yyVAL.boolExpr = yyS[yypt-0].boolExpr
		}
	case 145:
		yyVAL.boolExpr = yyS[yypt-0].boolExpr
	case 146:
		//line sql.y:714
		{
			yyVAL.boolExpr = &AndExpr{Op: string(yyS[yypt-1].str), Left: yyS[yypt-2].boolExpr, Right: yyS[yypt-0].boolExpr}
		}
	case 147:
		//line sql.y:718
		{
			yyVAL.boolExpr = &OrExpr{Op: string(yyS[yypt-1].str), Left: yyS[yypt-2].boolExpr, Right: yyS[yypt-0].boolExpr}
		}
	case 148:
		//line sql.y:722
		{
			yyVAL.boolExpr = &NotExpr{Op: string(yyS[yypt-1].str), Expr: yyS[yypt-0].boolExpr}
		}
	case 149:
		//line sql.y:726
		{
			yyVAL.boolExpr = &ParenBoolExpr{Expr: yyS[yypt-1].boolExpr}
		}
	case 150:
		//line sql.y:732
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyS[yypt-2].valExpr, Operator: yyS[yypt-1].str, Right: yyS[yypt-0].valExpr}
		}
	case 151:
		//line sql.y:736
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyS[yypt-2].valExpr, Operator: astIn, Right: yyS[yypt-0].tuple}
		}
	case 152:
		//line sql.y:740
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyS[yypt-3].valExpr, Operator: astNotIn, Right: yyS[yypt-0].tuple}
		}
	case 153:
		//line sql.y:744
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyS[yypt-2].valExpr, Operator: astLike, Right: yyS[yypt-0].valExpr}
		}
	case 154:
		//line sql.y:748
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyS[yypt-3].valExpr, Operator: astNotLike, Right: yyS[yypt-0].valExpr}
		}
	case 155:
		//line sql.y:752
		{
			yyVAL.boolExpr = &RangeCond{Left: yyS[yypt-4].valExpr, Operator: astBetween, From: yyS[yypt-2].valExpr, To: yyS[yypt-0].valExpr}
		}
	case 156:
		//line sql.y:756
		{
			yyVAL.boolExpr = &RangeCond{Left: yyS[yypt-5].valExpr, Operator: astNotBetween, From: yyS[yypt-2].valExpr, To: yyS[yypt-0].valExpr}
		}
	case 157:
		//line sql.y:760
		{
			yyVAL.boolExpr = &NullCheck{Operator: astNull, Expr: yyS[yypt-2].valExpr}
		}
	case 158:
		//line sql.y:764
		{
			yyVAL.boolExpr = &NullCheck{Operator: astNotNull, Expr: yyS[yypt-3].valExpr}
		}
	case 159:
		//line sql.y:768
		{
			yyVAL.boolExpr = &ExistsExpr{Subquery: yyS[yypt-0].subquery}
		}
	case 160:
		//line sql.y:774
		{
			yyVAL.str = astEQ
		}
	case 161:
		//line sql.y:778
		{
			yyVAL.str = astLT
		}
	case 162:
		//line sql.y:782
		{
			yyVAL.str = astGT
		}
	case 163:
		//line sql.y:786
		{
			yyVAL.str = astLE
		}
	case 164:
		//line sql.y:790
		{
			yyVAL.str = astGE
		}
	case 165:
		//line sql.y:794
		{
			yyVAL.str = astNE
		}
	case 166:
		//line sql.y:798
		{
			yyVAL.str = astNSE
		}
	case 167:
		//line sql.y:804
		{
			yyVAL.insRows = yyS[yypt-0].values
		}
	case 168:
		//line sql.y:808
		{
			yyVAL.insRows = yyS[yypt-0].selStmt
		}
	case 169:
		//line sql.y:814
		{
			yyVAL.values = Values{yyS[yypt-0].tuple}
		}
	case 170:
		//line sql.y:818
		{
			yyVAL.values = append(yyS[yypt-2].values, yyS[yypt-0].tuple)
		}
	case 171:
		//line sql.y:824
		{
			yyVAL.tuple = ValTuple(yyS[yypt-1].valExprs)
		}
	case 172:
		//line sql.y:828
		{
			yyVAL.tuple = yyS[yypt-0].subquery
		}
	case 173:
		//line sql.y:834
		{
			yyVAL.subquery = &Subquery{yyS[yypt-1].selStmt}
		}
	case 174:
		//line sql.y:840
		{
			yyVAL.valExprs = ValExprs{yyS[yypt-0].valExpr}
		}
	case 175:
		//line sql.y:844
		{
			yyVAL.valExprs = append(yyS[yypt-2].valExprs, yyS[yypt-0].valExpr)
		}
	case 176:
		//line sql.y:850
		{
			yyVAL.valExpr = yyS[yypt-0].valExpr
		}
	case 177:
		//line sql.y:854
		{
			yyVAL.valExpr = yyS[yypt-0].colName
		}
	case 178:
		//line sql.y:858
		{
			yyVAL.valExpr = yyS[yypt-0].tuple
		}
	case 179:
		//line sql.y:862
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astBitand, Right: yyS[yypt-0].valExpr}
		}
	case 180:
		//line sql.y:866
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astBitor, Right: yyS[yypt-0].valExpr}
		}
	case 181:
		//line sql.y:870
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astBitxor, Right: yyS[yypt-0].valExpr}
		}
	case 182:
		//line sql.y:874
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astPlus, Right: yyS[yypt-0].valExpr}
		}
	case 183:
		//line sql.y:878
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astMinus, Right: yyS[yypt-0].valExpr}
		}
	case 184:
		//line sql.y:882
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astMult, Right: yyS[yypt-0].valExpr}
		}
	case 185:
		//line sql.y:886
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astDiv, Right: yyS[yypt-0].valExpr}
		}
	case 186:
		//line sql.y:890
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyS[yypt-2].valExpr, Operator: astMod, Right: yyS[yypt-0].valExpr}
		}
	case 187:
		//line sql.y:894
		{
			yyVAL.valExpr = &UnaryExpr{Operator: yyS[yypt-1].byt, Expr: yyS[yypt-0].valExpr}
		}
	case 188:
		//line sql.y:898
		{
			yyVAL.valExpr = &FuncExpr{Name: strings.ToUpper(yyS[yypt-2].str)}
		}
	case 189:
		//line sql.y:902
		{
			yyVAL.valExpr = &FuncExpr{Name: strings.ToUpper(yyS[yypt-3].str), Exprs: yyS[yypt-1].selectExprs}
		}
	case 190:
		//line sql.y:906
		{
			yyVAL.valExpr = &FuncExpr{Name: strings.ToUpper(yyS[yypt-4].str), Distinct: true, Exprs: yyS[yypt-1].selectExprs}
		}
	case 191:
		//line sql.y:910
		{
			yyVAL.valExpr = &FuncExpr{Name: strings.ToUpper(yyS[yypt-3].str), Exprs: yyS[yypt-1].selectExprs}
		}
	case 192:
		//line sql.y:914
		{
			yyVAL.valExpr = yyS[yypt-0].caseExpr
		}
	case 193:
		//line sql.y:920
		{
			yyVAL.str = "IF"
		}
	case 194:
		//line sql.y:924
		{
			yyVAL.str = "VALUES"
		}
	case 195:
		//line sql.y:930
		{
			yyVAL.byt = astUnaryPlus
		}
	case 196:
		//line sql.y:934
		{
			yyVAL.byt = astUnaryMinus
		}
	case 197:
		//line sql.y:938
		{
			yyVAL.byt = astTilda
		}
	case 198:
		//line sql.y:944
		{
			yyVAL.caseExpr = &CaseExpr{Expr: yyS[yypt-3].valExpr, Whens: yyS[yypt-2].whens, Else: yyS[yypt-1].valExpr}
		}
	case 199:
		//line sql.y:949
		{
			yyVAL.valExpr = nil
		}
	case 200:
		//line sql.y:953
		{
			yyVAL.valExpr = yyS[yypt-0].valExpr
		}
	case 201:
		//line sql.y:959
		{
			yyVAL.whens = []*When{yyS[yypt-0].when}
		}
	case 202:
		//line sql.y:963
		{
			yyVAL.whens = append(yyS[yypt-1].whens, yyS[yypt-0].when)
		}
	case 203:
		//line sql.y:969
		{
			yyVAL.when = &When{Cond: yyS[yypt-2].boolExpr, Val: yyS[yypt-0].valExpr}
		}
	case 204:
		//line sql.y:974
		{
			yyVAL.valExpr = nil
		}
	case 205:
		//line sql.y:978
		{
			yyVAL.valExpr = yyS[yypt-0].valExpr
		}
	case 206:
		//line sql.y:984
		{
			yyVAL.colName = &ColName{Name: yyS[yypt-0].str}
		}
	case 207:
		//line sql.y:988
		{
			yyVAL.colName = &ColName{Qualifier: yyS[yypt-2].str, Name: yyS[yypt-0].str}
		}
	case 208:
		//line sql.y:994
		{
			yyVAL.valExpr = StrVal(yyS[yypt-0].str)
		}
	case 209:
		//line sql.y:998
		{
			yyVAL.valExpr = IntVal(yyS[yypt-0].str)
		}
	case 210:
		//line sql.y:1002
		{
			yyVAL.valExpr = NumVal(yyS[yypt-0].str)
		}
	case 211:
		//line sql.y:1006
		{
			yyVAL.valExpr = ValArg(yyS[yypt-0].str)
		}
	case 212:
		//line sql.y:1010
		{
			yyVAL.valExpr = &NullVal{}
		}
	case 213:
		//line sql.y:1015
		{
			yyVAL.valExprs = nil
		}
	case 214:
		//line sql.y:1019
		{
			yyVAL.valExprs = yyS[yypt-0].valExprs
		}
	case 215:
		//line sql.y:1024
		{
			yyVAL.boolExpr = nil
		}
	case 216:
		//line sql.y:1028
		{
			yyVAL.boolExpr = yyS[yypt-0].boolExpr
		}
	case 217:
		//line sql.y:1033
		{
			yyVAL.orderBy = nil
		}
	case 218:
		//line sql.y:1037
		{
			yyVAL.orderBy = yyS[yypt-0].orderBy
		}
	case 219:
		//line sql.y:1043
		{
			yyVAL.orderBy = OrderBy{yyS[yypt-0].order}
		}
	case 220:
		//line sql.y:1047
		{
			yyVAL.orderBy = append(yyS[yypt-2].orderBy, yyS[yypt-0].order)
		}
	case 221:
		//line sql.y:1053
		{
			yyVAL.order = &Order{Expr: yyS[yypt-1].valExpr, Direction: yyS[yypt-0].str}
		}
	case 222:
		//line sql.y:1058
		{
			yyVAL.str = astAsc
		}
	case 223:
		//line sql.y:1062
		{
			yyVAL.str = astAsc
		}
	case 224:
		//line sql.y:1066
		{
			yyVAL.str = astDesc
		}
	case 225:
		//line sql.y:1071
		{
			yyVAL.limit = nil
		}
	case 226:
		//line sql.y:1075
		{
			yyVAL.limit = &Limit{Rowcount: yyS[yypt-0].valExpr}
		}
	case 227:
		//line sql.y:1079
		{
			yyVAL.limit = &Limit{Offset: yyS[yypt-2].valExpr, Rowcount: yyS[yypt-0].valExpr}
		}
	case 228:
		//line sql.y:1083
		{
			yyVAL.limit = &Limit{Offset: yyS[yypt-0].valExpr, Rowcount: yyS[yypt-2].valExpr}
		}
	case 229:
		//line sql.y:1088
		{
			yyVAL.str = ""
		}
	case 230:
		//line sql.y:1092
		{
			yyVAL.str = astForUpdate
		}
	case 231:
		//line sql.y:1096
		{
			if yyS[yypt-1].str != "share" {
				yylex.Error("expecting share")
				return 1
			}
			if yyS[yypt-0].str != "mode" {
				yylex.Error("expecting mode")
				return 1
			}
			yyVAL.str = astShareMode
		}
	case 232:
		//line sql.y:1109
		{
			yyVAL.columns = nil
		}
	case 233:
		//line sql.y:1113
		{
			yyVAL.columns = yyS[yypt-1].columns
		}
	case 234:
		//line sql.y:1119
		{
			yyVAL.columns = Columns{&NonStarExpr{Expr: yyS[yypt-0].colName}}
		}
	case 235:
		//line sql.y:1123
		{
			yyVAL.columns = append(yyVAL.columns, &NonStarExpr{Expr: yyS[yypt-0].colName})
		}
	case 236:
		//line sql.y:1128
		{
			yyVAL.updateExprs = nil
		}
	case 237:
		//line sql.y:1132
		{
			yyVAL.updateExprs = yyS[yypt-0].updateExprs
		}
	case 238:
		//line sql.y:1138
		{
			yyVAL.updateExprs = UpdateExprs{yyS[yypt-0].updateExpr}
		}
	case 239:
		//line sql.y:1142
		{
			yyVAL.updateExprs = append(yyS[yypt-2].updateExprs, yyS[yypt-0].updateExpr)
		}
	case 240:
		//line sql.y:1148
		{
			yyVAL.updateExpr = &UpdateExpr{Name: yyS[yypt-2].colName, Expr: yyS[yypt-0].valExpr}
		}
	case 241:
		//line sql.y:1153
		{
			yyVAL.boolVal = false
		}
	case 242:
		//line sql.y:1155
		{
			yyVAL.boolVal = true
		}
	case 243:
		//line sql.y:1158
		{
			yyVAL.boolVal = false
		}
	case 244:
		//line sql.y:1160
		{
			yyVAL.boolVal = true
		}
	case 245:
		//line sql.y:1163
		{
			yyVAL.empty = struct{}{}
		}
	case 246:
		//line sql.y:1165
		{
			yyVAL.empty = struct{}{}
		}
	case 247:
		//line sql.y:1169
		{
			yyVAL.empty = struct{}{}
		}
	case 248:
		//line sql.y:1171
		{
			yyVAL.empty = struct{}{}
		}
	case 249:
		//line sql.y:1173
		{
			yyVAL.empty = struct{}{}
		}
	case 250:
		//line sql.y:1175
		{
			yyVAL.empty = struct{}{}
		}
	case 251:
		//line sql.y:1177
		{
			yyVAL.empty = struct{}{}
		}
	case 252:
		//line sql.y:1180
		{
			yyVAL.empty = struct{}{}
		}
	case 253:
		//line sql.y:1182
		{
			yyVAL.empty = struct{}{}
		}
	case 254:
		//line sql.y:1185
		{
			yyVAL.boolVal = false
		}
	case 255:
		//line sql.y:1187
		{
			yyVAL.boolVal = true
		}
	case 256:
		//line sql.y:1190
		{
			yyVAL.intVal = 0
		}
	case 257:
		//line sql.y:1192
		{
			yyVAL.intVal = yyS[yypt-1].intVal
		}
	case 258:
		//line sql.y:1196
		{
			i, ok := parseInt(yylex, yyS[yypt-0].str)
			if !ok {
				return 1
			}
			yyVAL.intVal = i
		}
	case 259:
		//line sql.y:1205
		{
			yyVAL.intVal2[0], yyVAL.intVal2[1] = 0, 0
		}
	case 260:
		//line sql.y:1207
		{
			yyVAL.intVal2[0], yyVAL.intVal2[1] = yyS[yypt-3].intVal, yyS[yypt-1].intVal
		}
	case 261:
		//line sql.y:1210
		{
			yyVAL.intVal2[0], yyVAL.intVal2[1] = 0, 0
		}
	case 262:
		//line sql.y:1212
		{
			yyVAL.intVal2[0], yyVAL.intVal2[1] = yyS[yypt-2].intVal, yyS[yypt-1].intVal
		}
	case 263:
		//line sql.y:1215
		{
			yyVAL.intVal = 0
		}
	case 264:
		//line sql.y:1217
		{
			yyVAL.intVal = yyS[yypt-0].intVal
		}
	case 265:
		//line sql.y:1220
		{
			yyVAL.boolVal = false
		}
	case 266:
		//line sql.y:1222
		{
			yyVAL.boolVal = true
		}
	case 267:
		//line sql.y:1225
		{
			yyVAL.empty = struct{}{}
		}
	case 268:
		//line sql.y:1227
		{
			yyVAL.empty = struct{}{}
		}
	case 269:
		//line sql.y:1230
		{
			yyVAL.str = ""
		}
	case 270:
		//line sql.y:1232
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 271:
		//line sql.y:1236
		{
			yyVAL.str = strings.ToLower(yyS[yypt-0].str)
		}
	case 272:
		//line sql.y:1239
		{
			forceEOF(yylex)
		}
	}
	goto yystack /* stack new state and value */
}
